"use client";

import { useEffect, useMemo, useState } from "react";
import {
  CheckCircle2, ChevronDown, ChevronUp, Clock3,
  PackageCheck, Plus, ReceiptText, Search, ShoppingBasket, TriangleAlert, X,
} from "lucide-react";
import { supabase } from "@/lib/supabase";
import { useEscapeToClose } from "@/lib/use-escape-close";

type Range = { start: string; end: string };
type Item = { id: string; name: string; sku: string | null; item_type: string; purchase_unit?: string | null; consumption_unit: string; areas: { id: string; name: string } | { id: string; name: string }[] | null };
type Supplier = { id: string; name: string; contact_name: string | null; phone: string | null; email: string | null; notes: string | null; is_active: boolean; total: number; purchase_count: number; last_purchase: string | null; average_purchase: number };
type SupplierItem = { supplier_id: string; item_id: string; is_preferred: boolean; item_name: string };
type PurchaseItem = { id: string; item_id: string; name: string; unit: string; quantity: number; received_quantity: number; unit_cost: number; total_cost: number; sector: string };
type Receipt = { id: string; received_at: string; notes: string | null; items: { item_id: string; name: string; quantity: number; unit_cost: number }[] };
type Purchase = { id: string; code: string; supplier_id: string; supplier_name: string | null; purchase_date: string; fulfillment_status: "ordered" | "awaiting" | "partially_received" | "received" | "cancelled"; payment_status: "pending" | "paid"; payment_method: string | null; due_date: string | null; paid_at: string | null; total_amount: number; notes: string | null; items: PurchaseItem[]; receipts: Receipt[] };
type PricePoint = { id: string; item_id: string; item_name: string; supplier_id: string; supplier_name: string | null; unit_cost: number; quantity: number; received_at: string };
type Replenishment = { item_id: string; name: string; sector: string; unit: string; current_stock: number | null; minimum_stock: number; reference_quantity: number | null; reference_days: number | null; suggested_quantity: number | null; status: string; supplier_id: string | null; supplier_name: string | null; last_price: number | null };
type PriceStat = { itemId: string; name: string; latest: number; previous: number | null; change: number | null; min: number; max: number; points: PricePoint[] };
type Dashboard = { period_start: string; period_end: string; summary: { total: number; awaiting: number; partial: number; received: number; payment_pending: number; replenishment_items: number }; suppliers: Supplier[]; supplier_items: SupplierItem[]; purchases: Purchase[]; price_history: PricePoint[]; replenishment: Replenishment[] };

const EMPTY: Dashboard = { period_start: "", period_end: "", summary: { total: 0, awaiting: 0, partial: 0, received: 0, payment_pending: 0, replenishment_items: 0 }, suppliers: [], supplier_items: [], purchases: [], price_history: [], replenishment: [] };
const MONEY = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const NUMBER = new Intl.NumberFormat("pt-BR", { maximumFractionDigits: 2 });
const DATE = new Intl.DateTimeFormat("pt-BR", { timeZone: "UTC" });
const STATUS_LABEL: Record<Purchase["fulfillment_status"], string> = { ordered: "Pedido", awaiting: "Aguardando", partially_received: "Parcial", received: "Recebido", cancelled: "Cancelado" };

function one<T>(value: T | T[] | null): T | null { return Array.isArray(value) ? value[0] ?? null : value; }
function dateLabel(value: string | null) { return value ? DATE.format(new Date(`${value.slice(0, 10)}T00:00:00Z`)) : "—"; }
function decimal(value: string) { const result = Number(value.replace(",", ".")); return Number.isFinite(result) ? result : 0; }

export function PurchasesPage({ businessId, range, items }: { businessId: string; userId: string; range: Range; items: Item[] }) {
  const [dashboard, setDashboard] = useState<Dashboard>(EMPTY);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [tab, setTab] = useState<"overview" | "orders" | "suppliers" | "replenishment" | "prices">("overview");
  const [supplierModal, setSupplierModal] = useState<Supplier | "new" | null>(null);
  const [purchaseModal, setPurchaseModal] = useState<{ initial?: Replenishment[] } | null>(null);
  const [receivePurchase, setReceivePurchase] = useState<Purchase | null>(null);
  const [expanded, setExpanded] = useState<string | null>(null);
  const [query, setQuery] = useState("");
  const [supplierFilter, setSupplierFilter] = useState("all");
  const [statusFilter, setStatusFilter] = useState("all");
  const [paymentFilter, setPaymentFilter] = useState("all");
  const [selectedRestock, setSelectedRestock] = useState<Set<string>>(() => new Set());

  async function reload() {
    setLoading(true); setError("");
    const { data, error: rpcError } = await supabase.rpc("get_purchases_dashboard", { p_business_id: Number(businessId), p_period_start: range.start, p_period_end: range.end });
    if (rpcError) setError("Não foi possível carregar compras e fornecedores agora.");
    else setDashboard((data as Dashboard | null) ?? EMPTY);
    setLoading(false);
  }
  useEffect(() => {
    let cancelled = false;
    async function load() {
      setLoading(true); setError("");
      const { data, error: rpcError } = await supabase.rpc("get_purchases_dashboard", { p_business_id: Number(businessId), p_period_start: range.start, p_period_end: range.end });
      if (cancelled) return;
      if (rpcError) setError("Não foi possível carregar compras e fornecedores agora.");
      else setDashboard((data as Dashboard | null) ?? EMPTY);
      setLoading(false);
    }
    void load();
    return () => { cancelled = true; };
  }, [businessId, range.start, range.end]);

  const priceStats = useMemo(() => {
    const grouped = new Map<string, PricePoint[]>();
    dashboard.price_history.forEach((row) => grouped.set(row.item_id, [...(grouped.get(row.item_id) ?? []), row]));
    return [...grouped.entries()].map(([itemId, values]) => {
      const sorted = values.sort((a, b) => b.received_at.localeCompare(a.received_at));
      const latest = sorted[0]; const previous = sorted[1];
      const change = previous?.unit_cost > 0 ? (latest.unit_cost - previous.unit_cost) / previous.unit_cost : null;
      return { itemId, name: latest.item_name, latest: latest.unit_cost, previous: previous?.unit_cost ?? null, change, min: Math.min(...sorted.map((row) => Number(row.unit_cost))), max: Math.max(...sorted.map((row) => Number(row.unit_cost))), points: sorted };
    }).sort((a, b) => Number(b.change ?? -Infinity) - Number(a.change ?? -Infinity));
  }, [dashboard.price_history]);
  const topSupplier = dashboard.suppliers.find((supplier) => Number(supplier.total) > 0) ?? null;
  const highestIncrease = priceStats.find((row) => row.change !== null && row.change > 0) ?? null;
  const filteredPurchases = dashboard.purchases.filter((purchase) => {
    const text = `${purchase.code} ${purchase.supplier_name ?? ""} ${purchase.items.map((item) => item.name).join(" ")}`.toLocaleLowerCase("pt-BR");
    return text.includes(query.toLocaleLowerCase("pt-BR")) && (supplierFilter === "all" || purchase.supplier_id === supplierFilter) && (statusFilter === "all" || purchase.fulfillment_status === statusFilter) && (paymentFilter === "all" || purchase.payment_status === paymentFilter);
  });
  const selectedSuggestions = dashboard.replenishment.filter((row) => selectedRestock.has(row.item_id));

  async function changeStatus(purchase: Purchase, status: "awaiting" | "cancelled") {
    const { error: rpcError } = await supabase.rpc("update_purchase_order_status", { p_business_id: Number(businessId), p_purchase_id: Number(purchase.id), p_status: status });
    if (rpcError) return setError(rpcError.message);
    await reload();
  }
  async function togglePayment(purchase: Purchase) {
    const next = purchase.payment_status === "paid" ? "pending" : "paid";
    const { error: rpcError } = await supabase.rpc("update_purchase_payment", { p_business_id: Number(businessId), p_purchase_id: Number(purchase.id), p_payment_status: next, p_payment_method: purchase.payment_method });
    if (rpcError) return setError(rpcError.message);
    await reload();
  }

  return <section className="purchase-page">
    <div className="module-hero"><div className="module-icon"><ShoppingBasket size={19} /></div><div><p>Compras e abastecimento</p><h2>Comprar melhor, receber com controle</h2><span>Pedidos, fornecedores, recebimentos, preços e reposição ligados ao estoque virtual.</span></div><button onClick={() => setPurchaseModal({})}>Nova compra</button></div>
    {loading && <p className="purchase-loading"><Clock3 size={15} />Carregando compras e preços reais...</p>}
    {error && <div className="data-warning"><TriangleAlert size={14} /><div><strong>{error}</strong><span>Nenhum pedido, custo ou saldo foi alterado.</span></div><button onClick={reload}>Tentar novamente</button></div>}
    <div className="purchase-kpis">
      <PurchaseKpi label="Comprado no período" value={MONEY.format(Number(dashboard.summary.total))} note={`${dashboard.purchases.filter((row) => row.fulfillment_status !== "cancelled").length} compra(s)`} tone="green" />
      <PurchaseKpi label="Aguardando chegada" value={String(dashboard.summary.awaiting)} note="Pedidos sem recebimento" tone="yellow" />
      <PurchaseKpi label="Recebimento parcial" value={String(dashboard.summary.partial)} note="Ainda há quantidade pendente" tone="yellow" />
      <PurchaseKpi label="Recebidas" value={String(dashboard.summary.received)} note="Entrada confirmada no estoque" tone="green" />
      <PurchaseKpi label="Pendente de pagamento" value={MONEY.format(Number(dashboard.summary.payment_pending))} note="Refletido uma única vez em despesas" tone="red" />
      <PurchaseKpi label="Itens para comprar" value={String(dashboard.replenishment.length)} note="Alertas e sugestões do estoque" tone="blue" />
      <PurchaseKpi label="Maior fornecedor" value={topSupplier?.name ?? "Sem dados"} note={topSupplier ? MONEY.format(Number(topSupplier.total)) : "Cadastre a primeira compra"} tone="neutral" />
      <PurchaseKpi label="Maior alta de preço" value={highestIncrease?.change === null || !highestIncrease ? "Sem dados" : `${NUMBER.format(highestIncrease.change * 100)}%`} note={highestIncrease?.name ?? "São necessários 2 recebimentos"} tone="red" />
    </div>
    <div className="purchase-tabs" role="tablist" aria-label="Visões de compras">
      <button className={tab === "overview" ? "active" : ""} onClick={() => setTab("overview")}>Visão geral</button>
      <button className={tab === "orders" ? "active" : ""} onClick={() => setTab("orders")}>Compras <span>{dashboard.purchases.length}</span></button>
      <button className={tab === "replenishment" ? "active" : ""} onClick={() => setTab("replenishment")}>Itens para comprar <span>{dashboard.replenishment.length}</span></button>
      <button className={tab === "suppliers" ? "active" : ""} onClick={() => setTab("suppliers")}>Fornecedores <span>{dashboard.suppliers.length}</span></button>
      <button className={tab === "prices" ? "active" : ""} onClick={() => setTab("prices")}>Histórico de preços</button>
    </div>

    {tab === "overview" && <PurchaseOverview dashboard={dashboard} priceStats={priceStats} onOpenOrders={() => setTab("orders")} onOpenReplenishment={() => setTab("replenishment")} />}
    {tab === "orders" && <div className="purchase-section">
      <div className="purchase-section-head"><div><p>Histórico e acompanhamento</p><h3>Todas as compras do período</h3></div><button onClick={() => setPurchaseModal({})}><Plus size={15} /> Nova compra</button></div>
      <div className="module-toolbar purchase-toolbar"><label><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar código, fornecedor ou produto" /></label><select value={supplierFilter} onChange={(event) => setSupplierFilter(event.target.value)}><option value="all">Todos os fornecedores</option>{dashboard.suppliers.map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.name}</option>)}</select><select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option value="all">Todos os status</option><option value="ordered">Pedido</option><option value="awaiting">Aguardando</option><option value="partially_received">Parcial</option><option value="received">Recebido</option><option value="cancelled">Cancelado</option></select><select value={paymentFilter} onChange={(event) => setPaymentFilter(event.target.value)}><option value="all">Pago e pendente</option><option value="pending">Pendente</option><option value="paid">Pago</option></select><span className="table-count">{filteredPurchases.length} compra(s)</span></div>
      <div className="purchase-order-list">{filteredPurchases.length ? filteredPurchases.map((purchase) => <article key={purchase.id} className={`purchase-order ${expanded === purchase.id ? "expanded" : ""}`}><button className="purchase-order-main" onClick={() => setExpanded(expanded === purchase.id ? null : purchase.id)}><span><strong>{purchase.code}</strong><small>{dateLabel(purchase.purchase_date)}</small></span><span><strong>{purchase.supplier_name ?? "Fornecedor removido"}</strong><small>{purchase.items.length} item(ns)</small></span><span><StatusBadge status={purchase.fulfillment_status} /><small>{purchase.items.reduce((sum, item) => sum + Number(item.received_quantity), 0)} de {purchase.items.reduce((sum, item) => sum + Number(item.quantity), 0)} recebidos</small></span><span><PaymentBadge status={purchase.payment_status} /><small>{purchase.due_date ? `Vence ${dateLabel(purchase.due_date)}` : "Sem vencimento"}</small></span><strong>{MONEY.format(Number(purchase.total_amount))}</strong>{expanded === purchase.id ? <ChevronUp size={18} /> : <ChevronDown size={18} />}</button>{expanded === purchase.id && <div className="purchase-order-detail"><div className="purchase-detail-items"><div className="purchase-detail-row header"><span>Item</span><span>Setor</span><span>Pedido</span><span>Recebido</span><span>Preço unit.</span><span>Total</span></div>{purchase.items.map((item) => <div className="purchase-detail-row" key={item.id}><strong>{item.name}</strong><span>{item.sector}</span><span>{NUMBER.format(item.quantity)} {item.unit}</span><span>{NUMBER.format(item.received_quantity)} {item.unit}</span><span>{MONEY.format(item.unit_cost)}</span><strong>{MONEY.format(item.total_cost)}</strong></div>)}</div>{purchase.receipts.length > 0 && <div className="purchase-receipts"><strong>Recebimentos</strong>{purchase.receipts.map((receipt) => <span key={receipt.id}><CheckCircle2 size={14} />{new Date(receipt.received_at).toLocaleString("pt-BR")} · {receipt.items.map((item) => `${NUMBER.format(item.quantity)} ${item.name}`).join(", ")}</span>)}</div>}<div className="purchase-order-actions">{purchase.fulfillment_status === "ordered" && <button onClick={() => changeStatus(purchase, "awaiting")}>Marcar como aguardando</button>}{["ordered","awaiting","partially_received"].includes(purchase.fulfillment_status) && <button className="primary" onClick={() => setReceivePurchase(purchase)}><PackageCheck size={15} /> Confirmar recebimento</button>} {purchase.fulfillment_status !== "cancelled" && <button onClick={() => togglePayment(purchase)}>{purchase.payment_status === "paid" ? "Voltar para pendente" : "Marcar como pago"}</button>}{["ordered","awaiting"].includes(purchase.fulfillment_status) && <button className="danger" onClick={() => changeStatus(purchase, "cancelled")}>Cancelar pedido</button>}</div></div>}</article>) : <Empty text="Nenhuma compra encontrada no período ou nos filtros atuais." />}</div>
    </div>}

    {tab === "replenishment" && <div className="purchase-section"><div className="purchase-section-head"><div><p>Decisão de abastecimento</p><h3>Itens para comprar</h3><span>Previsões são sugestões; revise a quantidade antes de criar o pedido.</span></div>{selectedSuggestions.length > 0 && <button onClick={() => setPurchaseModal({ initial: selectedSuggestions })}><ShoppingBasket size={15} /> Montar lista ({selectedSuggestions.length})</button>}</div><div className="replenishment-table responsive-table"><div className="replenishment-row header"><span></span><span>Produto</span><span>Setor</span><span>Estoque atual</span><span>Mínimo</span><span>Referência</span><span>Sugestão</span><span>Fornecedor</span><span>Último preço</span></div>{dashboard.replenishment.length ? dashboard.replenishment.map((row) => <div className="replenishment-row" key={row.item_id}><label><input type="checkbox" checked={selectedRestock.has(row.item_id)} onChange={(event) => setSelectedRestock((current) => { const next = new Set(current); if (event.target.checked) next.add(row.item_id); else next.delete(row.item_id); return next; })} aria-label={`Selecionar ${row.name}`} /></label><strong>{row.name}<small>{row.status === "insufficient_data" ? "Saldo inicial necessário" : "Estoque em atenção"}</small></strong><span>{row.sector}</span><span>{row.current_stock === null ? "—" : `${NUMBER.format(row.current_stock)} ${row.unit}`}</span><span>{NUMBER.format(row.minimum_stock)} {row.unit}</span><span>{row.reference_days ? `${NUMBER.format(Number(row.reference_quantity))} · ${row.reference_days} sextas` : "Sem histórico suficiente"}</span><strong>{row.suggested_quantity ? `${NUMBER.format(row.suggested_quantity)} ${row.unit}` : "Revisar"}</strong><span>{row.supplier_name ?? "Não relacionado"}</span><span>{row.last_price === null ? "—" : MONEY.format(row.last_price)}</span></div>) : <Empty text="Nenhum item possui alerta ou sugestão de reposição confiável neste momento." />}</div></div>}

    {tab === "suppliers" && <div className="purchase-section"><div className="purchase-section-head"><div><p>Parceiros de abastecimento</p><h3>Fornecedores</h3></div><button onClick={() => setSupplierModal("new")}><Plus size={15} /> Novo fornecedor</button></div><div className="supplier-grid">{dashboard.suppliers.length ? dashboard.suppliers.map((supplier, index) => { const linked = dashboard.supplier_items.filter((row) => row.supplier_id === supplier.id); const share = Number(dashboard.summary.total) > 0 ? Number(supplier.total) / Number(dashboard.summary.total) : 0; return <button key={supplier.id} className="supplier-card" onClick={() => setSupplierModal(supplier)}><header><span><b>{String(index + 1).padStart(2,"0")}</b><strong>{supplier.name}</strong></span><small className={supplier.is_active ? "active" : "inactive"}>{supplier.is_active ? "Ativo" : "Inativo"}</small></header><div className="supplier-card-value"><strong>{MONEY.format(Number(supplier.total))}</strong><span>{NUMBER.format(share * 100)}% das compras</span></div><div className="supplier-card-metrics"><span><small>Compras</small><strong>{supplier.purchase_count}</strong></span><span><small>Ticket médio</small><strong>{supplier.purchase_count ? MONEY.format(Number(supplier.average_purchase)) : "—"}</strong></span><span><small>Última compra</small><strong>{dateLabel(supplier.last_purchase)}</strong></span></div><p>{linked.length ? linked.slice(0,4).map((row) => row.item_name).join(" · ") : "Nenhum produto relacionado"}{linked.length > 4 ? ` +${linked.length - 4}` : ""}</p></button>; }) : <Empty text="Nenhum fornecedor cadastrado. Cadastre somente parceiros reais do bar." />}</div></div>}

    {tab === "prices" && <PricesView stats={priceStats} history={dashboard.price_history} />}
    {supplierModal && <SupplierModal businessId={businessId} supplier={supplierModal === "new" ? null : supplierModal} items={items} linked={dashboard.supplier_items} onClose={() => setSupplierModal(null)} onSaved={async () => { setSupplierModal(null); await reload(); }} />}
    {purchaseModal && <PurchaseModal businessId={businessId} suppliers={dashboard.suppliers.filter((row) => row.is_active)} items={items} initial={purchaseModal.initial ?? []} onClose={() => setPurchaseModal(null)} onSaved={async () => { setPurchaseModal(null); setSelectedRestock(new Set()); setTab("orders"); await reload(); }} />}
    {receivePurchase && <ReceiptModal businessId={businessId} purchase={receivePurchase} onClose={() => setReceivePurchase(null)} onSaved={async () => { setReceivePurchase(null); await reload(); }} />}
  </section>;
}

function PurchaseOverview({ dashboard, priceStats, onOpenOrders, onOpenReplenishment }: { dashboard: Dashboard; priceStats: PriceStat[]; onOpenOrders: () => void; onOpenReplenishment: () => void }) {
  const activePurchases = dashboard.purchases.filter((row) => !["received","cancelled"].includes(row.fulfillment_status));
  return <div className="purchase-overview-grid"><article className="purchase-panel purchase-flow-panel"><div className="purchase-panel-head"><div><p>Fluxo operacional</p><h3>Pedidos em andamento</h3></div><button onClick={onOpenOrders}>Ver todas</button></div>{activePurchases.length ? activePurchases.slice(0,5).map((purchase) => <div className="purchase-flow-row" key={purchase.id}><StatusBadge status={purchase.fulfillment_status} /><span><strong>{purchase.code} · {purchase.supplier_name}</strong><small>{purchase.items.map((item) => item.name).slice(0,3).join(", ")}</small></span><strong>{MONEY.format(Number(purchase.total_amount))}</strong></div>) : <Empty text="Não há pedidos aguardando recebimento." />}</article><article className="purchase-panel"><div className="purchase-panel-head"><div><p>Reposição conectada</p><h3>Prioridades de compra</h3></div><button onClick={onOpenReplenishment}>Abrir lista</button></div>{dashboard.replenishment.length ? dashboard.replenishment.slice(0,6).map((row) => <div className="purchase-priority-row" key={row.item_id}><span><strong>{row.name}</strong><small>{row.supplier_name ?? "Sem fornecedor relacionado"}</small></span><b>{row.suggested_quantity ? `~${NUMBER.format(row.suggested_quantity)} ${row.unit}` : "Revisar"}</b></div>) : <Empty text="Sem alertas de reposição confiáveis." />}</article><article className="purchase-panel"><div className="purchase-panel-head"><div><p>Pressão de custos</p><h3>Maiores variações</h3></div></div>{priceStats.length ? priceStats.slice(0,6).map((row) => <div className="purchase-price-alert" key={row.itemId}><span><strong>{row.name}</strong><small>{row.previous === null ? "Somente um preço recebido" : `${MONEY.format(row.previous)} → ${MONEY.format(row.latest)}`}</small></span><b className={Number(row.change) > .1 ? "high" : Number(row.change) < 0 ? "down" : ""}>{row.change === null ? "—" : `${row.change > 0 ? "+" : ""}${NUMBER.format(row.change * 100)}%`}</b></div>) : <Empty text="O histórico começa após os primeiros recebimentos." />}</article></div>;
}
function PricesView({ stats, history }: { stats: PriceStat[]; history: PricePoint[] }) {
  const [selected, setSelected] = useState(stats[0]?.itemId ?? "");
  const current = stats.find((row) => row.itemId === selected) ?? stats[0];
  const comparisons = current ? [...current.points.reduce((latest, row) => { if (!latest.has(row.supplier_id)) latest.set(row.supplier_id, row); return latest; }, new Map<string, PricePoint>()).values()].sort((a,b) => a.unit_cost-b.unit_cost) : [];
  return <div className="purchase-section"><div className="purchase-section-head"><div><p>Custos comprovados</p><h3>Histórico de preços recebidos</h3><span>Somente mercadorias efetivamente recebidas entram nesta análise.</span></div>{stats.length > 0 && <select value={current?.itemId ?? ""} onChange={(event) => setSelected(event.target.value)}>{stats.map((row) => <option key={row.itemId} value={row.itemId}>{row.name}</option>)}</select>}</div>{current ? <><div className="price-summary-grid"><PurchaseKpi label="Último preço" value={MONEY.format(current.latest)} note="Recebimento mais recente" tone="green" /><PurchaseKpi label="Preço anterior" value={current.previous === null ? "—" : MONEY.format(current.previous)} note="Comparação imediatamente anterior" tone="neutral" /><PurchaseKpi label="Variação" value={current.change === null ? "—" : `${current.change > 0 ? "+" : ""}${NUMBER.format(current.change*100)}%`} note={Number(current.change) >= .1 ? "Aumento relevante" : "Entre os últimos recebimentos"} tone={Number(current.change) >= .1 ? "red" : "blue"} /><PurchaseKpi label="Faixa histórica" value={`${MONEY.format(current.min)} — ${MONEY.format(current.max)}`} note={`${current.points.length} recebimento(s)`} tone="neutral" /></div><div className="price-analysis-grid"><article className="purchase-panel"><div className="purchase-panel-head"><div><p>Evolução</p><h3>{current.name}</h3></div></div><div className="price-timeline">{[...current.points].reverse().map((point) => <div key={point.id}><span>{new Date(point.received_at).toLocaleDateString("pt-BR")}<small>{point.supplier_name}</small></span><i><em style={{ width: `${point.unit_cost / Math.max(current.max,1) * 100}%` }} /></i><strong>{MONEY.format(point.unit_cost)}</strong></div>)}</div></article><article className="purchase-panel"><div className="purchase-panel-head"><div><p>Comparação real</p><h3>Fornecedores</h3></div></div>{comparisons.map((row,index) => <div className="supplier-comparison" key={row.supplier_id}><b>{index+1}</b><span><strong>{row.supplier_name}</strong><small>Último preço recebido</small></span><strong>{MONEY.format(row.unit_cost)}</strong></div>)}</article></div></> : <Empty text={history.length ? "Selecione um produto." : "Ainda não existem recebimentos para formar histórico de preço."} />}</div>;
}

function SupplierModal({ businessId, supplier, items, linked, onClose, onSaved }: { businessId: string; supplier: Supplier | null; items: Item[]; linked: SupplierItem[]; onClose: () => void; onSaved: () => Promise<void> }) {
  const [form,setForm] = useState({ name:supplier?.name ?? "",contact_name:supplier?.contact_name ?? "",phone:supplier?.phone ?? "",email:supplier?.email ?? "",notes:supplier?.notes ?? "",is_active:supplier?.is_active ?? true });
  const [selected,setSelected] = useState<Set<string>>(() => new Set(supplier ? linked.filter((row)=>row.supplier_id===supplier.id).map((row)=>row.item_id) : []));
  const [query,setQuery] = useState(""); const [saving,setSaving] = useState(false); const [error,setError] = useState("");
  async function save(event: React.FormEvent) { event.preventDefault(); if (!form.name.trim()) return setError("Informe o nome do fornecedor."); setSaving(true); const { error: rpcError } = await supabase.rpc("save_supplier",{p_business_id:Number(businessId),p_supplier_id:supplier?Number(supplier.id):null,p_name:form.name,p_contact_name:form.contact_name,p_phone:form.phone,p_email:form.email,p_notes:form.notes,p_is_active:form.is_active,p_item_ids:[...selected].map(Number)}); if (rpcError){setError(rpcError.message);setSaving(false);return;} await onSaved(); }
  const visible=items.filter((item)=>`${item.name} ${item.sku??""}`.toLowerCase().includes(query.toLowerCase()));
  return <Modal title={supplier ? "Editar fornecedor" : "Novo fornecedor"} subtitle="Cadastre somente dados reais e relacione os itens normalmente fornecidos." onClose={onClose}><form onSubmit={save}><div className="form-grid"><label className="span-2"><span>Nome do fornecedor</span><input value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})} autoFocus /></label><label><span>Pessoa de contato</span><input value={form.contact_name} onChange={(e)=>setForm({...form,contact_name:e.target.value})} /></label><label><span>Telefone</span><input value={form.phone} onChange={(e)=>setForm({...form,phone:e.target.value})} /></label><label><span>E-mail</span><input type="email" value={form.email} onChange={(e)=>setForm({...form,email:e.target.value})} /></label><label><span>Status</span><select value={form.is_active?"active":"inactive"} onChange={(e)=>setForm({...form,is_active:e.target.value==="active"})}><option value="active">Ativo</option><option value="inactive">Inativo</option></select></label><label className="span-2"><span>Observações</span><textarea value={form.notes} onChange={(e)=>setForm({...form,notes:e.target.value})} /></label></div><div className="supplier-item-picker"><strong>Produtos fornecidos</strong><label><Search size={15}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Buscar produto ou ingrediente" /></label><div>{visible.map((item)=><label key={item.id}><input type="checkbox" checked={selected.has(item.id)} onChange={(e)=>setSelected((current)=>{const next=new Set(current);if(e.target.checked)next.add(item.id);else next.delete(item.id);return next;})}/><span>{item.name}<small>{one(item.areas)?.name ?? "Geral"} · {item.consumption_unit}</small></span></label>)}</div></div>{error&&<p className="form-error">{error}</p>}<ModalActions saving={saving} onClose={onClose} label="Salvar fornecedor" /></form></Modal>;
}

type PurchaseDraft = { itemId:string; quantity:string; unit:string; unitCost:string };
function PurchaseModal({ businessId, suppliers, items, initial, onClose, onSaved }: { businessId:string; suppliers:Supplier[]; items:Item[]; initial:Replenishment[]; onClose:()=>void; onSaved:()=>Promise<void> }) {
  const [supplierId,setSupplierId]=useState(initial.find((row)=>row.supplier_id)?.supplier_id ?? suppliers[0]?.id ?? "");
  const [date,setDate]=useState(new Date().toISOString().slice(0,10)); const [payment,setPayment]=useState(""); const [due,setDue]=useState(""); const [notes,setNotes]=useState("");
  const [lines,setLines]=useState<PurchaseDraft[]>(()=>initial.length?initial.map((row)=>({itemId:row.item_id,quantity:String(row.suggested_quantity??""),unit:row.unit,unitCost:row.last_price===null?"":String(row.last_price)})):[{itemId:items[0]?.id??"",quantity:"",unit:items[0]?.purchase_unit??items[0]?.consumption_unit??"un",unitCost:""}]);
  const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  function patchLine(index:number,patch:Partial<PurchaseDraft>){setLines((current)=>current.map((line,i)=>i===index?{...line,...patch}:line));}
  function addLine(){const next=items.find((item)=>!lines.some((line)=>line.itemId===item.id));if(next)setLines((current)=>[...current,{itemId:next.id,quantity:"",unit:next.purchase_unit??next.consumption_unit,unitCost:""}]);}
  const total=lines.reduce((sum,line)=>sum+decimal(line.quantity)*decimal(line.unitCost),0);
  async function save(event:React.FormEvent){event.preventDefault();if(!supplierId)return setError("Cadastre e selecione um fornecedor.");if(lines.some((line)=>!line.itemId||decimal(line.quantity)<=0||decimal(line.unitCost)<0||line.unitCost.trim()===""))return setError("Revise os itens, quantidades e preços.");if(new Set(lines.map((line)=>line.itemId)).size!==lines.length)return setError("Remova itens repetidos.");setSaving(true);const {error:rpcError}=await supabase.rpc("create_purchase_order",{p_business_id:Number(businessId),p_supplier_id:Number(supplierId),p_purchase_date:date,p_payment_method:payment,p_due_date:due||null,p_notes:notes,p_items:lines.map((line)=>({item_id:Number(line.itemId),quantity:decimal(line.quantity),unit:line.unit,unit_cost:decimal(line.unitCost)}))});if(rpcError){setError(rpcError.message);setSaving(false);return;}await onSaved();}
  return <Modal title="Registrar nova compra" subtitle="O pedido cria a obrigação financeira, mas o estoque só aumenta quando o recebimento for confirmado." onClose={onClose}><form onSubmit={save}><div className="form-grid"><label><span>Fornecedor</span><select value={supplierId} onChange={(e)=>setSupplierId(e.target.value)}><option value="">Selecione</option>{suppliers.map((supplier)=><option key={supplier.id} value={supplier.id}>{supplier.name}</option>)}</select></label><label><span>Data da compra</span><input type="date" value={date} onChange={(e)=>setDate(e.target.value)} /></label><label><span>Forma de pagamento</span><input value={payment} onChange={(e)=>setPayment(e.target.value)} placeholder="PIX, boleto, cartão..." /></label><label><span>Vencimento</span><input type="date" value={due} onChange={(e)=>setDue(e.target.value)} /></label></div><div className="purchase-line-editor"><div className="purchase-line header"><span>Produto / ingrediente</span><span>Quantidade</span><span>Unidade</span><span>Preço unit.</span><span>Total</span><span></span></div>{lines.map((line,index)=>{const selected=items.find((item)=>item.id===line.itemId);return <div className="purchase-line" key={`${line.itemId}-${index}`}><select value={line.itemId} onChange={(e)=>{const item=items.find((candidate)=>candidate.id===e.target.value);patchLine(index,{itemId:e.target.value,unit:item?.purchase_unit??item?.consumption_unit??"un"});}}>{items.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><input type="number" min="0.0001" step="0.0001" value={line.quantity} onChange={(e)=>patchLine(index,{quantity:e.target.value})}/><input value={line.unit} onChange={(e)=>patchLine(index,{unit:e.target.value})}/><input type="number" min="0" step="0.0001" value={line.unitCost} onChange={(e)=>patchLine(index,{unitCost:e.target.value})} placeholder={selected?"0,00":""}/><strong>{MONEY.format(decimal(line.quantity)*decimal(line.unitCost))}</strong><button type="button" onClick={()=>setLines((current)=>current.filter((_,i)=>i!==index))} aria-label="Remover item"><X size={15}/></button></div>})}<button type="button" className="add-purchase-line" onClick={addLine}><Plus size={14}/> Adicionar item</button></div><div className="purchase-order-total"><label><span>Observações</span><textarea value={notes} onChange={(e)=>setNotes(e.target.value)} /></label><span><small>Valor total da compra</small><strong>{MONEY.format(total)}</strong></span></div>{error&&<p className="form-error">{error}</p>}<ModalActions saving={saving} onClose={onClose} label="Registrar pedido" /></form></Modal>;
}

function ReceiptModal({businessId,purchase,onClose,onSaved}:{businessId:string;purchase:Purchase;onClose:()=>void;onSaved:()=>Promise<void>}){
  const pending=purchase.items.filter((item)=>item.received_quantity<item.quantity);const [quantities,setQuantities]=useState<Record<string,string>>({});const [receivedAt,setReceivedAt]=useState(new Date().toISOString().slice(0,16));const [notes,setNotes]=useState("");const [saving,setSaving]=useState(false);const [error,setError]=useState("");
  async function save(){const lines=pending.map((item)=>({purchase_item_id:Number(item.id),quantity:decimal(quantities[item.id]??"")})).filter((line)=>line.quantity>0);if(!lines.length)return setError("Informe a quantidade recebida de ao menos um item.");if(lines.some((line)=>line.quantity>Number(pending.find((item)=>Number(item.id)===line.purchase_item_id)!.quantity)-Number(pending.find((item)=>Number(item.id)===line.purchase_item_id)!.received_quantity)))return setError("Uma quantidade ultrapassa o saldo pendente.");setSaving(true);const {error:rpcError}=await supabase.rpc("receive_purchase_order",{p_business_id:Number(businessId),p_purchase_id:Number(purchase.id),p_received_at:new Date(receivedAt).toISOString(),p_notes:notes,p_items:lines});if(rpcError){setError(rpcError.message);setSaving(false);return;}await onSaved();}
  return <Modal title={`Receber ${purchase.code}`} subtitle="Confirme somente o que chegou fisicamente. Cada quantidade registrada entra no estoque e atualiza o histórico de custo." onClose={onClose}><div className="receipt-lines"><div className="receipt-line header"><span>Item</span><span>Pedido</span><span>Já recebido</span><span>Pendente</span><span>Receber agora</span></div>{pending.map((item)=><div className="receipt-line" key={item.id}><strong>{item.name}<small>{item.unit}</small></strong><span>{NUMBER.format(item.quantity)}</span><span>{NUMBER.format(item.received_quantity)}</span><span>{NUMBER.format(item.quantity-item.received_quantity)}</span><input type="number" min="0" max={item.quantity-item.received_quantity} step="0.0001" value={quantities[item.id]??""} onChange={(e)=>setQuantities({...quantities,[item.id]:e.target.value})}/></div>)}</div><div className="form-grid"><label><span>Data e hora do recebimento</span><input type="datetime-local" value={receivedAt} max={new Date().toISOString().slice(0,16)} onChange={(e)=>setReceivedAt(e.target.value)}/></label><label><span>Observação</span><input value={notes} onChange={(e)=>setNotes(e.target.value)} placeholder="Ex.: entrega parcial"/></label></div>{error&&<p className="form-error">{error}</p>}<ModalActions saving={saving} onClose={onClose} onSave={save} label="Confirmar recebimento" /></Modal>;
}

function Modal({title,subtitle,onClose,children}:{title:string;subtitle:string;onClose:()=>void;children:React.ReactNode}){useEscapeToClose(onClose);return <div className="modal-backdrop"><div className="modal-card purchase-modal" role="dialog" aria-modal="true" aria-labelledby="purchase-modal-title"><button className="modal-close" onClick={onClose} aria-label="Fechar"><X size={19}/></button><p className="page-kicker">Compras e fornecedores</p><h2 id="purchase-modal-title">{title}</h2><p className="modal-description">{subtitle}</p>{children}</div></div>}
function ModalActions({saving,onClose,onSave,label}:{saving:boolean;onClose:()=>void;onSave?:()=>void;label:string}){return <div className="modal-actions"><button type="button" className="modal-secondary" onClick={onClose}>Cancelar</button><button type={onSave?"button":"submit"} className="modal-primary" disabled={saving} onClick={onSave}>{saving?"Salvando...":label}</button></div>}
function PurchaseKpi({label,value,note,tone}:{label:string;value:string;note:string;tone:"green"|"yellow"|"red"|"blue"|"neutral"}){return <article className={`purchase-kpi ${tone}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
function StatusBadge({status}:{status:Purchase["fulfillment_status"]}){return <span className={`purchase-status ${status}`}>{STATUS_LABEL[status]}</span>}
function PaymentBadge({status}:{status:Purchase["payment_status"]}){return <span className={`payment-status ${status}`}>{status==="paid"?"Pago":"Pendente"}</span>}
function Empty({text}:{text:string}){return <div className="purchase-empty"><ReceiptText size={25}/><span>{text}</span></div>}
