alter table public.expenses add column if not exists source_type text;
alter table public.expenses add column if not exists source_id bigint;
alter table public.expenses add column if not exists recurrence_end date;
alter table public.expenses add constraint expenses_source_type_check
  check (source_type is null or source_type in ('purchase','work_shift','personnel_cost','payroll_closing','structural_cost'));
create unique index if not exists expenses_source_unique_idx
  on public.expenses (business_id, source_type, source_id) where source_type is not null;

create table public.employees (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  main_area_id bigint references public.areas(id) on delete set null,
  name text not null check (length(trim(name)) between 2 and 120),
  role_title text not null check (length(trim(role_title)) between 2 and 100),
  employment_type text not null default 'employee' check (employment_type in ('employee','freelancer','day_worker','other')),
  remuneration_type text not null default 'monthly' check (remuneration_type in ('monthly','daily','hourly','other')),
  start_date date not null default current_date,
  is_active boolean not null default true,
  notes text,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.employee_compensation_history (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  employee_id bigint not null references public.employees(id) on delete cascade,
  remuneration_type text not null check (remuneration_type in ('monthly','daily','hourly','other')),
  amount numeric(14,2) not null check (amount >= 0),
  effective_from date not null,
  notes text,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  unique (employee_id, effective_from)
);

create table public.work_shifts (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  employee_id bigint not null references public.employees(id) on delete restrict,
  area_id bigint references public.areas(id) on delete set null,
  shift_date date not null,
  input_mode text not null default 'times' check (input_mode in ('times','direct_hours','daily')),
  start_time time,
  end_time time,
  break_minutes integer not null default 0 check (break_minutes between 0 and 1440),
  hours_worked numeric(8,2) not null default 0 check (hours_worked >= 0 and hours_worked <= 24),
  rate_snapshot numeric(14,2) not null default 0 check (rate_snapshot >= 0),
  amount_due numeric(14,2) not null default 0 check (amount_due >= 0),
  payment_status text not null default 'pending' check (payment_status in ('pending','paid','cancelled')),
  paid_at timestamptz,
  payment_method text,
  notes text,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (input_mode <> 'times' or (start_time is not null and end_time is not null))
);

create table public.personnel_cost_entries (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  employee_id bigint references public.employees(id) on delete set null,
  area_id bigint references public.areas(id) on delete set null,
  cost_date date not null,
  cost_type text not null check (cost_type in ('monthly_salary','overtime','charges','benefit','bonus','additional','other')),
  description text not null check (length(trim(description)) between 2 and 160),
  amount numeric(14,2) not null check (amount > 0),
  payment_status text not null default 'pending' check (payment_status in ('pending','paid','cancelled')),
  paid_at timestamptz,
  payment_method text,
  notes text,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.payroll_closings (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  period_start date not null,
  period_end date not null,
  status text not null default 'pending' check (status in ('pending','paid','cancelled')),
  total_amount numeric(14,2) not null default 0,
  paid_at timestamptz,
  payment_method text,
  notes text,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  check (period_start <= period_end)
);

create table public.payroll_closing_items (
  id bigint generated by default as identity primary key,
  closing_id bigint not null references public.payroll_closings(id) on delete cascade,
  employee_id bigint not null references public.employees(id) on delete restrict,
  amount numeric(14,2) not null check (amount >= 0),
  hours_worked numeric(8,2) not null default 0,
  shift_ids bigint[] not null default '{}',
  personnel_cost_ids bigint[] not null default '{}',
  unique (closing_id, employee_id)
);

alter table public.work_shifts add column payroll_closing_id bigint references public.payroll_closings(id) on delete set null;
alter table public.personnel_cost_entries add column payroll_closing_id bigint references public.payroll_closings(id) on delete set null;

create table public.structural_costs (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  area_id bigint references public.areas(id) on delete set null,
  name text not null check (length(trim(name)) between 2 and 140),
  structure_type text not null check (structure_type in ('terrain','container','bathroom','other')),
  monthly_amount numeric(14,2) not null check (monthly_amount > 0),
  effective_from date not null,
  effective_to date,
  is_active boolean not null default true,
  notes text,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (effective_to is null or effective_to >= effective_from)
);

create index employees_business_active_idx on public.employees (business_id, is_active, name);
create index compensation_employee_date_idx on public.employee_compensation_history (employee_id, effective_from desc);
create index work_shifts_business_date_idx on public.work_shifts (business_id, shift_date, employee_id);
create index personnel_costs_business_date_idx on public.personnel_cost_entries (business_id, cost_date, employee_id);
create index payroll_closings_business_period_idx on public.payroll_closings (business_id, period_start, period_end);
create index structural_costs_business_dates_idx on public.structural_costs (business_id, effective_from, effective_to);

alter table public.employees enable row level security;
alter table public.employee_compensation_history enable row level security;
alter table public.work_shifts enable row level security;
alter table public.personnel_cost_entries enable row level security;
alter table public.payroll_closings enable row level security;
alter table public.payroll_closing_items enable row level security;
alter table public.structural_costs enable row level security;

create policy employees_member_all on public.employees for all to authenticated using ((select private.is_business_member(business_id))) with check ((select private.is_business_member(business_id)));
create policy compensation_member_all on public.employee_compensation_history for all to authenticated using ((select private.is_business_member(business_id))) with check ((select private.is_business_member(business_id)));
create policy shifts_member_all on public.work_shifts for all to authenticated using ((select private.is_business_member(business_id))) with check ((select private.is_business_member(business_id)));
create policy personnel_costs_member_all on public.personnel_cost_entries for all to authenticated using ((select private.is_business_member(business_id))) with check ((select private.is_business_member(business_id)));
create policy payroll_closings_member_all on public.payroll_closings for all to authenticated using ((select private.is_business_member(business_id))) with check ((select private.is_business_member(business_id)));
create policy payroll_items_member_all on public.payroll_closing_items for all to authenticated
  using (exists (select 1 from public.payroll_closings c where c.id = closing_id and (select private.is_business_member(c.business_id))))
  with check (exists (select 1 from public.payroll_closings c where c.id = closing_id and (select private.is_business_member(c.business_id))));
create policy structural_costs_member_all on public.structural_costs for all to authenticated using ((select private.is_business_member(business_id))) with check ((select private.is_business_member(business_id)));

grant select, insert, update, delete on public.employees, public.employee_compensation_history, public.work_shifts,
  public.personnel_cost_entries, public.payroll_closings, public.payroll_closing_items, public.structural_costs to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create or replace function public.save_work_shift(
  p_business_id bigint, p_employee_id bigint, p_shift_date date, p_area_id bigint,
  p_input_mode text, p_start_time time, p_end_time time, p_break_minutes integer,
  p_direct_hours numeric, p_rate_override numeric, p_notes text default null
) returns bigint language plpgsql security invoker set search_path = '' as $$
declare
  v_employee public.employees%rowtype; v_rate numeric; v_hours numeric; v_amount numeric; v_shift_id bigint;
  v_start timestamp; v_end timestamp;
begin
  if (select auth.uid()) is null or not (select private.is_business_member(p_business_id)) then raise exception 'Acesso negado ao negócio'; end if;
  select * into v_employee from public.employees where id=p_employee_id and business_id=p_business_id;
  if not found then raise exception 'Funcionário não encontrado'; end if;
  select amount into v_rate from public.employee_compensation_history where employee_id=p_employee_id and effective_from<=p_shift_date order by effective_from desc,id desc limit 1;
  v_rate := coalesce(p_rate_override,v_rate,0);
  if p_input_mode='times' then
    if p_start_time is null or p_end_time is null then raise exception 'Informe entrada e saída'; end if;
    v_start := p_shift_date + p_start_time; v_end := p_shift_date + p_end_time;
    if v_end <= v_start then v_end := v_end + interval '1 day'; end if;
    v_hours := greatest(0, extract(epoch from (v_end-v_start))/3600 - coalesce(p_break_minutes,0)/60.0);
  elsif p_input_mode='daily' then v_hours := coalesce(p_direct_hours,0);
  else v_hours := coalesce(p_direct_hours,0); end if;
  if v_hours > 24 then raise exception 'A jornada não pode ultrapassar 24 horas'; end if;
  v_amount := case when p_input_mode='daily' or v_employee.remuneration_type='daily' then v_rate when v_employee.remuneration_type='hourly' then round(v_hours*v_rate,2) else 0 end;
  insert into public.work_shifts (business_id,employee_id,area_id,shift_date,input_mode,start_time,end_time,break_minutes,hours_worked,rate_snapshot,amount_due,notes,created_by)
  values (p_business_id,p_employee_id,coalesce(p_area_id,v_employee.main_area_id),p_shift_date,p_input_mode,p_start_time,p_end_time,coalesce(p_break_minutes,0),round(v_hours,2),v_rate,v_amount,nullif(trim(p_notes),''),(select auth.uid())) returning id into v_shift_id;
  if v_amount > 0 then
    insert into public.expenses (business_id,area_id,category,description,expense_date,due_date,amount,status,is_recurring,cost_behavior,source_type,source_id,created_by)
    values (p_business_id,coalesce(p_area_id,v_employee.main_area_id),'Funcionários/pessoal','Jornada · '||v_employee.name,p_shift_date,p_shift_date,v_amount,'pending',false,'variable','work_shift',v_shift_id,(select auth.uid()));
  end if;
  return v_shift_id;
end $$;

create or replace function public.save_personnel_cost(
  p_business_id bigint, p_employee_id bigint, p_area_id bigint, p_cost_date date,
  p_cost_type text, p_description text, p_amount numeric, p_paid boolean,
  p_payment_method text default null, p_notes text default null
) returns bigint language plpgsql security invoker set search_path = '' as $$
declare v_id bigint; v_area bigint;
begin
  if (select auth.uid()) is null or not (select private.is_business_member(p_business_id)) then raise exception 'Acesso negado ao negócio'; end if;
  if p_amount<=0 then raise exception 'O valor deve ser maior que zero'; end if;
  select coalesce(p_area_id,e.main_area_id) into v_area from public.employees e where e.id=p_employee_id and e.business_id=p_business_id;
  insert into public.personnel_cost_entries (business_id,employee_id,area_id,cost_date,cost_type,description,amount,payment_status,paid_at,payment_method,notes,created_by)
  values (p_business_id,p_employee_id,v_area,p_cost_date,p_cost_type,trim(p_description),p_amount,case when p_paid then 'paid' else 'pending' end,case when p_paid then now() end,nullif(trim(p_payment_method),''),nullif(trim(p_notes),''),(select auth.uid())) returning id into v_id;
  insert into public.expenses (business_id,area_id,category,description,expense_date,due_date,paid_at,amount,payment_method,status,is_recurring,cost_behavior,source_type,source_id,created_by)
  values (p_business_id,v_area,'Funcionários/pessoal',trim(p_description),p_cost_date,p_cost_date,case when p_paid then now() end,p_amount,nullif(trim(p_payment_method),''),case when p_paid then 'completed'::public.record_status else 'pending'::public.record_status end,false,case when p_cost_type='monthly_salary' then 'fixed' else 'variable' end,'personnel_cost',v_id,(select auth.uid()));
  return v_id;
end $$;

create or replace function public.set_personnel_payment(p_business_id bigint,p_source_type text,p_source_id bigint,p_paid boolean,p_payment_method text default null)
returns void language plpgsql security invoker set search_path='' as $$
begin
  if (select auth.uid()) is null or not (select private.is_business_member(p_business_id)) then raise exception 'Acesso negado ao negócio'; end if;
  if p_source_type='work_shift' then update public.work_shifts set payment_status=case when p_paid then 'paid' else 'pending' end,paid_at=case when p_paid then now() end,payment_method=nullif(trim(p_payment_method),'') where id=p_source_id and business_id=p_business_id;
  elsif p_source_type='personnel_cost' then update public.personnel_cost_entries set payment_status=case when p_paid then 'paid' else 'pending' end,paid_at=case when p_paid then now() end,payment_method=nullif(trim(p_payment_method),'') where id=p_source_id and business_id=p_business_id;
  else raise exception 'Origem inválida'; end if;
  update public.expenses set status=case when p_paid then 'completed'::public.record_status else 'pending'::public.record_status end,paid_at=case when p_paid then now() end,payment_method=nullif(trim(p_payment_method),'') where business_id=p_business_id and source_type=p_source_type and source_id=p_source_id;
end $$;

create or replace function public.create_payroll_closing(p_business_id bigint,p_period_start date,p_period_end date,p_notes text default null)
returns bigint language plpgsql security invoker set search_path='' as $$
declare v_id bigint; v_total numeric;
begin
  if (select auth.uid()) is null or not (select private.is_business_member(p_business_id)) then raise exception 'Acesso negado ao negócio'; end if;
  if p_period_start>p_period_end then raise exception 'Período inválido'; end if;
  insert into public.payroll_closings (business_id,period_start,period_end,notes,created_by)
  values (p_business_id,p_period_start,p_period_end,nullif(trim(p_notes),''),(select auth.uid())) returning id into v_id;
  insert into public.payroll_closing_items (closing_id,employee_id,amount,hours_worked,shift_ids,personnel_cost_ids)
  select v_id,e.id,coalesce(s.amount,0)+coalesce(c.amount,0),coalesce(s.hours,0),coalesce(s.ids,'{}'),coalesce(c.ids,'{}')
  from public.employees e
  left join lateral (select sum(amount_due) amount,sum(hours_worked) hours,array_agg(id) ids from public.work_shifts where employee_id=e.id and business_id=p_business_id and shift_date between p_period_start and p_period_end and payment_status='pending' and payroll_closing_id is null) s on true
  left join lateral (select sum(amount) amount,array_agg(id) ids from public.personnel_cost_entries where employee_id=e.id and business_id=p_business_id and cost_date between p_period_start and p_period_end and payment_status='pending' and payroll_closing_id is null) c on true
  where e.business_id=p_business_id and (coalesce(s.amount,0)+coalesce(c.amount,0))>0;
  if not exists(select 1 from public.payroll_closing_items where closing_id=v_id) then delete from public.payroll_closings where id=v_id; raise exception 'Não há valores pendentes para fechar neste período'; end if;
  update public.work_shifts s set payroll_closing_id=v_id where s.id=any((select coalesce(array_agg(x),'{}') from public.payroll_closing_items i cross join unnest(i.shift_ids) x where i.closing_id=v_id));
  update public.personnel_cost_entries c set payroll_closing_id=v_id where c.id=any((select coalesce(array_agg(x),'{}') from public.payroll_closing_items i cross join unnest(i.personnel_cost_ids) x where i.closing_id=v_id));
  select sum(amount) into v_total from public.payroll_closing_items where closing_id=v_id;
  update public.payroll_closings set total_amount=coalesce(v_total,0) where id=v_id;
  return v_id;
end $$;

create or replace function public.pay_payroll_closing(p_business_id bigint,p_closing_id bigint,p_payment_method text)
returns void language plpgsql security invoker set search_path='' as $$
begin
  if (select auth.uid()) is null or not (select private.is_business_member(p_business_id)) then raise exception 'Acesso negado ao negócio'; end if;
  update public.payroll_closings set status='paid',paid_at=now(),payment_method=nullif(trim(p_payment_method),'') where id=p_closing_id and business_id=p_business_id and status='pending';
  if not found then raise exception 'Fechamento pendente não encontrado'; end if;
  update public.work_shifts set payment_status='paid',paid_at=now(),payment_method=nullif(trim(p_payment_method),'') where business_id=p_business_id and payroll_closing_id=p_closing_id;
  update public.personnel_cost_entries set payment_status='paid',paid_at=now(),payment_method=nullif(trim(p_payment_method),'') where business_id=p_business_id and payroll_closing_id=p_closing_id;
  update public.expenses e set status='completed',paid_at=now(),payment_method=nullif(trim(p_payment_method),'')
    where e.business_id=p_business_id and ((e.source_type='work_shift' and exists(select 1 from public.work_shifts s where s.id=e.source_id and s.payroll_closing_id=p_closing_id)) or (e.source_type='personnel_cost' and exists(select 1 from public.personnel_cost_entries c where c.id=e.source_id and c.payroll_closing_id=p_closing_id)));
end $$;

create or replace function public.save_structural_cost(
  p_business_id bigint,p_area_id bigint,p_name text,p_structure_type text,p_monthly_amount numeric,
  p_effective_from date,p_effective_to date default null,p_notes text default null
) returns bigint language plpgsql security invoker set search_path='' as $$
declare v_id bigint;
begin
  if (select auth.uid()) is null or not (select private.is_business_member(p_business_id)) then raise exception 'Acesso negado ao negócio'; end if;
  insert into public.structural_costs (business_id,area_id,name,structure_type,monthly_amount,effective_from,effective_to,notes,created_by)
  values (p_business_id,p_area_id,trim(p_name),p_structure_type,p_monthly_amount,p_effective_from,p_effective_to,nullif(trim(p_notes),''),(select auth.uid())) returning id into v_id;
  insert into public.expenses (business_id,area_id,category,description,expense_date,due_date,amount,status,is_recurring,cost_behavior,source_type,source_id,recurrence_end,created_by)
  values (p_business_id,p_area_id,'Aluguel',trim(p_name),p_effective_from,p_effective_from,p_monthly_amount,'pending',true,'fixed','structural_cost',v_id,p_effective_to,(select auth.uid()));
  return v_id;
end $$;

create or replace function public.get_personnel_dashboard(p_business_id bigint,p_period_start date,p_period_end date)
returns jsonb language plpgsql stable security invoker set search_path='' as $$
declare v_result jsonb;
begin
 if (select auth.uid()) is null or not (select private.is_business_member(p_business_id)) then raise exception 'Acesso negado ao negócio'; end if;
 if p_period_start is null or p_period_end is null or p_period_start>p_period_end or p_period_end-p_period_start>366 then raise exception 'Período inválido'; end if;
 select jsonb_build_object(
  'employees',(select coalesce(jsonb_agg(to_jsonb(x) order by x.is_active desc,x.name),'[]') from (select e.*,a.name area_name,(select jsonb_agg(to_jsonb(h) order by h.effective_from desc) from public.employee_compensation_history h where h.employee_id=e.id) compensation_history from public.employees e left join public.areas a on a.id=e.main_area_id where e.business_id=p_business_id) x),
  'shifts',(select coalesce(jsonb_agg(to_jsonb(x) order by x.shift_date desc,x.id desc),'[]') from (select s.*,e.name employee_name,e.role_title,a.name area_name from public.work_shifts s join public.employees e on e.id=s.employee_id left join public.areas a on a.id=s.area_id where s.business_id=p_business_id and s.shift_date between p_period_start and p_period_end and s.payment_status<>'cancelled') x),
  'costs',(select coalesce(jsonb_agg(to_jsonb(x) order by x.cost_date desc,x.id desc),'[]') from (select c.*,e.name employee_name,a.name area_name from public.personnel_cost_entries c left join public.employees e on e.id=c.employee_id left join public.areas a on a.id=c.area_id where c.business_id=p_business_id and c.cost_date between p_period_start and p_period_end and c.payment_status<>'cancelled') x),
  'structures',(select coalesce(jsonb_agg(to_jsonb(x) order by x.is_active desc,x.name),'[]') from (select s.*,a.name area_name from public.structural_costs s left join public.areas a on a.id=s.area_id where s.business_id=p_business_id) x),
  'closings',(select coalesce(jsonb_agg(to_jsonb(x) order by x.period_end desc,x.id desc),'[]') from (select c.*,(select coalesce(jsonb_agg(jsonb_build_object('employee_id',i.employee_id,'employee_name',e.name,'amount',i.amount,'hours_worked',i.hours_worked)),'[]') from public.payroll_closing_items i join public.employees e on e.id=i.employee_id where i.closing_id=c.id) items from public.payroll_closings c where c.business_id=p_business_id and c.status<>'cancelled') x),
  'revenue_cents',(select coalesce(sum(t.net_amount_cents),0) from public.zig_sales_transactions t where t.business_id=p_business_id and t.operational_date between p_period_start and p_period_end and not t.is_refunded)
 ) into v_result;
 return v_result;
end $$;

revoke all on function public.save_work_shift(bigint,bigint,date,bigint,text,time,time,integer,numeric,numeric,text) from public,anon;
revoke all on function public.save_personnel_cost(bigint,bigint,bigint,date,text,text,numeric,boolean,text,text) from public,anon;
revoke all on function public.set_personnel_payment(bigint,text,bigint,boolean,text) from public,anon;
revoke all on function public.create_payroll_closing(bigint,date,date,text) from public,anon;
revoke all on function public.pay_payroll_closing(bigint,bigint,text) from public,anon;
revoke all on function public.save_structural_cost(bigint,bigint,text,text,numeric,date,date,text) from public,anon;
revoke all on function public.get_personnel_dashboard(bigint,date,date) from public,anon;
grant execute on function public.save_work_shift(bigint,bigint,date,bigint,text,time,time,integer,numeric,numeric,text) to authenticated;
grant execute on function public.save_personnel_cost(bigint,bigint,bigint,date,text,text,numeric,boolean,text,text) to authenticated;
grant execute on function public.set_personnel_payment(bigint,text,bigint,boolean,text) to authenticated;
grant execute on function public.create_payroll_closing(bigint,date,date,text) to authenticated;
grant execute on function public.pay_payroll_closing(bigint,bigint,text) to authenticated;
grant execute on function public.save_structural_cost(bigint,bigint,text,text,numeric,date,date,text) to authenticated;
grant execute on function public.get_personnel_dashboard(bigint,date,date) to authenticated;
